// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreApp.Data.Concrete;

#nullable disable

namespace StoreApp.Web.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    partial class StoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("StoreApp.Data.Concrete.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Telefon",
                            Description = "Güzel Telefon",
                            Name = "Samsung S25",
                            Price = 1000m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Telefon",
                            Description = "Güzel Telefon",
                            Name = "Samsung S24",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Telefon",
                            Description = "Güzel Telefon",
                            Name = "Samsung S23",
                            Price = 3000m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Telefon",
                            Description = "Güzel Telefon",
                            Name = "Samsung S22",
                            Price = 4000m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Telefon",
                            Description = "Güzel Telefon",
                            Name = "Samsung S21",
                            Price = 5000m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Telefon",
                            Description = "Güzel Telefon",
                            Name = "Samsung S20",
                            Price = 6000m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Telefon",
                            Description = "Güzel Telefon",
                            Name = "Samsung S10",
                            Price = 7000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
